&1 attributes reach threshold of &2
SAP/code-pal-for-abap pull request #168
Opened 2020-10-07 20:29 UTC by lucasborin

2020-10-08 07:22 UTC, estevao-schultz-neto-SAP requested changes
"reaching"

2020-10-08 14:08 UTC, lucasborin commented on src/checks/y_check_number_methods.clas.abap
> +    set_check_message( '&1 methods attributes reaching threshold of &2' ).
number of methods, not attributes

2020-10-08 14:08 UTC, lucasborin commented on src/checks/y_check_num_output_parameter.clas.abap
> +    set_check_message( '&1 attributes reaching threshold of &2' ).
number of output parameters, not attributes

2020-10-08 14:12 UTC, lucasborin commented
@estevao-schultz-neto-SAP : Could you please check it agian?

2020-10-09 06:33 UTC, estevao-schultz-neto-SAP commented
fine!!

2020-10-09 06:35 UTC, merged