changing default severity
SAP/code-pal-for-abap pull request #376
Opened 2021-04-14 16:25 UTC by lucasborin

Closes #368

2021-04-14 16:27 UTC, lucasborin commented on src/checks/y_check_branch_coverage.clas.abap
> +    version = '0002'.
version = version + 1.

2021-04-14 16:27 UTC, lucasborin commented on src/checks/y_check_procedure_coverage.clas.abap
> +    version = '0002'.
version = version + 1.

2021-04-14 16:27 UTC, lucasborin commented on src/checks/y_check_returning_name.clas.abap
> +    version = version + 1.
move it to top

2021-04-14 16:28 UTC, lucasborin commented on src/checks/y_check_statement_coverage.clas.abap
> +    version = version + 1.
move to top

2021-04-14 16:46 UTC, lucasborin commented
it corrupts the variant 😢

2021-04-14 16:54 UTC, lucasborin commented
"corrupts" => it forces the user to review the new customizing on each check. To avoid manual efforts in the upgrade, let's keep the same Check version.

2021-04-15 08:35 UTC, estevao-schultz-neto-SAP requested changes
I've just adjusted minor things in the text/docu.

2021-04-15 11:00 UTC, lucasborin commented on pages/how-to-configure.md
> +⚠️The below documentation is valid for our own `Profile Management Tool` (transaction: `Y_CODE_PAL_PROFILE`) feature only.
The transaction is not duplicated (line 9 and 22). How about if we link to the `Profile Management Tool` page?

2021-04-15 11:31 UTC, lucasborin commented on pages/how-to-configure.md
> +💡 The tool is compatible with the SAP Code Inspector framework (`SCI` / `SCII`) and you can launch it using your own SCI/SCII variant(s). Alternatively, you may also use the tool by means of defining
@estevao-schultz-neto-SAP: it looks redundant as we mentioned the transactions twice.

2021-04-15 18:12 UTC, estevao-schultz-neto-SAP approved these changes

2021-04-15 18:22 UTC, merged